### ISSUE TITLE
Whats the difference between `include/import_role` and `roles:` ?

### ISSUE THREAD

**Issue by dzintars** [oswee/ignite#27]
Whats the difference between `include/import_role` and `roles:` ?
```yaml
---
- hosts: localhost
  connection: local
  tasks:
    - include_role:
        name: ericsysmin.collection.rolename
      vars: param: some_var
```
and the 
```yaml
---
- name: Converge
  hosts: all
  roles:
    - role: domain.system.somerole
      when: ansible_os_family == "RedHat"
```
